close all;
clear;
clc;

setup;

scripts_names = {...
    "test_1a", ...
    "test_1b", ...
    "test_1c", ...
    "test_1d", ...
    "test_2a", ...
    "test_2b", ...
    "test_2c", ...
    "test_2d", ...
    "test_3a", ...
    "test_3b", ...
    "test_3c", ...
    "test_3d", ...
    };
% parpool(4);

parfor i = 1:length(scripts_names)
    run_test(scripts_names, i);
end


delete(gcp);



function run_test(sources, idx)
    try
        run(sources{idx});
    catch
        f = fopen("parpool.log", "a");
        fprintf(f, "Error while computing %s\n", sources{idx});
    end
end
